package com.myspace.ruleselection;

/**
 * This class was automatically generated by the data modeler tool.
 */
import org.drools.runtime.rule.RuleContext;

public class Helper implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Helper() {
    }

    
    
       public static boolean checkTaxonomy(RuleContext ruleCont , String value){
           
           return true;
           
       }



}