package com.myspace.ruleselection;

/**
 * This class was automatically generated by the data modeler tool.
 */
//import org.drools.runtime.rule.RuleContext;
import org.drools.core.spi.KnowledgeHelper;
public class Helper implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Helper() {
    }

    
    
       public static boolean checkTaxonomy(KnowledgeHelper ruleCont , String value){
           
           return true;
           
       }



}