package com.myspace.ruleselection;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Helper implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Helper() {
    }




}