package com.myspace.ruleselection;

//import org.drools.runtime.rule.RuleContext;
import org.drools.core.spi.KnowledgeHelper;

//function boolean checkTaxonomy(RuleContext kdrools , String taxonomy) {
    
  //  return true;
//}

//from row number: 1
rule "Row 1 EligibilityRules"
	@channel("IWC/UD")

	dialect "mvel"
	when
		trans : Transaction( type == "MUTUAL-FUNDS-COST-BASIS-SETTINGS" , productCode == "10" )
	then
		trans.setEligibility( true );
end

//from row number: 2
rule "Row 2 EligibilityRules"
	@channel("IWC/UD")
	dialect "mvel"
	when
		trans : Transaction( type == "MUTUAL-FUNDS-EXCHANGE" , productCode == "6" )
	then
		trans.setEligibility( true );
end

//from row number: 3
rule "Row 3 EligibilityRules"
	@channel("UD")
	dialect "mvel"
	when
		trans : Transaction( type == "MUTUAL-FUNDS-PURCHASE" , productCode == "10" )
	then
		trans.setEligibility( true );
end

//from row number: 4
rule "Row 4 EligibilityRules"
	@channel("IWC")
	dialect "mvel"
	when
		trans : Transaction( type == "MUTUAL-FUNDS-REDEEM" , productCode == "20" )
	then
		trans.setEligibility( true );
end