package com.myspace.ruleselection;


import java.util.Map;
import java.util.List;

global java.lang.String Taxonomy;
global java.lang.String TaxonomyValue;

function boolean checkTaxonomy(Object channel , String taxonomy) {

     List channels = (List)channel;
     boolean isenabled = channels.contains(taxonomy);
    
    return isenabled;
  
}

rule "Initialize"
	dialect "mvel"
//	ruleflow-group "initialize"
    @channel(value = {"IN"})
	when
		exists (Transaction( )) 
	then
		System.out.println("Initialization rule fired");
end

//from row number: 1
rule "Row 1 EligibilityRules"
	@channel(value = {"IWC","UD"})
    //enabled(checkTaxonomy1(drools,TaxonomyValue))
    enabled( checkTaxonomy(rule.metaData["channel"], TaxonomyValue))
	dialect "mvel"
	//ruleflow-group "Eligibility"
	when
		trans : Transaction(  productCode == "10" )
	then
		trans.setEligibility( true );
end

//from row number: 1
rule "Row 1 EligibilityRulesforIWC"
	@channel(value = {"IWC"})
   // enabled(checkTaxonomy1(drools))
     enabled( checkTaxonomy(rule.metaData["channel"] , TaxonomyValue ))
	dialect "mvel"
//	ruleflow-group "Eligibility"
	when
		trans : Transaction(  productCode == "10" )
	then
		trans.setEligibility( true );
end

//from row number: 2
rule "Row 2 EligibilityRules"
    @channel(value = {"IWC","UD"})
	dialect "mvel"
//	ruleflow-group "Eligibility"
	 //enabled(checkTaxonomy1(drools))
	  enabled( checkTaxonomy(rule.metaData["channel"] ,TaxonomyValue))
	when
		trans : Transaction( type == "MUTUAL-FUNDS-EXCHANGE" , productCode == "6" )
	then
		trans.setEligibility( true );
end

//from row number: 3
rule "Row 3 EligibilityRules"
	@channel(value = {"UD"})
	dialect "mvel"
	 //enabled(checkTaxonomy1(drools))
	  enabled(checkTaxonomy( rule.metaData["channel"] , TaxonomyValue ))
//	 ruleflow-group "Eligibility"
	when
		trans : Transaction( type == "MUTUAL-FUNDS-COST-BASIS-SETTINGS" , productCode == "10" )
	then
		trans.setEligibility( true );
end

//from row number: 4
rule "Row 4 EligibilityRules"
   
	@channel(value = {"IWC"})
	dialect "mvel"
	 //enabled(checkTaxonomy1(drools))
	  enabled(checkTaxonomy(rule.metaData["channel"] , TaxonomyValue ) )
	// ruleflow-group "Eligibility"
	when
		trans : Transaction( type == "MUTUAL-FUNDS-REDEEM" , productCode == "20" )
	then
		trans.setEligibility( true );
end